# Generated by Django 3.1.2 on 2020-12-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20201202_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='realtor_en',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='realtor_ru',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='realtor_uz',
        ),
        migrations.AddField(
            model_name='listing',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
    ]
